/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../android_developerment/sdk_new/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_test_studio_JniUtli */

#ifndef _Included_com_test_studio_JniUtli
#define _Included_com_test_studio_JniUtli
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_studio_JniUtli
 * Method:    sayHellow
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_studio_JniUtli_sayHellow
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
